### ISSUE TITLE
Uncaught Error: Redis connection in broken state: connection timeout exceeded.

### ISSUE THREAD

**Issue by lgybetter** [tosone/atom-parsing#1]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.15.0 x64
**Electron**: 1.3.13
**OS**: Ubuntu 16.04.2
**Thrown From**: [parsing](https://github.com/tosone/atom-parsing) package 1.1.6

### Stack Trace

Uncaught Error: Redis connection in broken state: connection timeout exceeded.

```
At events.js:160

Error: Redis connection in broken state: connection timeout exceeded.
    at RedisClient.connection_gone (/packages/parsing/node_modules/redis/index.js:644:19)
    at /packages/parsing/node_modules/redis/index.js:289:14)
    at Socket.g (events.js:286:16)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:493:12)
```

### Commands

```
```

### Non-Core Packages

```
parsing 1.1.6 
```

**Comment by asicminer001** [comment]
help

**Comment by tosone** [comment]
What are you doing on this? If you are in emergency situation, contact with me wechat: 17010209162
